# Generated by Django 3.2.9 on 2022-06-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='a',
            field=models.CharField(default='aaa', max_length=5),
            preserve_default=False,
        ),
    ]
