# Generated by Django 3.2.9 on 2022-06-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='a',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
    ]
