# Generated by Django 3.2.9 on 2022-06-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220622_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='a',
            field=models.CharField(default='111', max_length=5),
            preserve_default=False,
        ),
    ]
