# Generated by Django 3.2.9 on 2022-06-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_category_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='a',
        ),
    ]
